First Pull request for addition of Landing Page
Def-Hacks-CS-Outreach/def-hacks-learn pull request #6
Opened 2020-09-13 03:57 UTC by Saloni242

# Description

The time period of development (from fork to pull request): 

Forked on 11th Sept 2020 and made changes on 12th Sept 2020. Added the Landing Page as Home page and then added Particles.js in the background of Landing Page

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

2020-09-13 18:57 UTC, GreenBayRules requested changes
nice job! please fix these formatting changes and we can merge

2020-09-13 18:57 UTC, GreenBayRules commented on src/Footer.js
> +import { Grid, Navbar,NavItem,Nav} from 'react-bootstrap';
Let's keep formatting/whitespace all consistent.

You can do `import {Grid, Navbar, NavItem, Nav} from 'react-bootstrap';` or  `import { Grid, Navbar, NavItem, Nav } from 'react-bootstrap';` but keep it consistent

2020-09-13 18:57 UTC, GreenBayRules commented on src/Home.js
> +import {Form,FormControl,Button} from 'react-bootstrap';
same thing here

2020-09-13 18:57 UTC, GreenBayRules commented on src/Home.js
> +      }} />
Can you indent lines 15-17?

2020-09-19 04:52 UTC, GreenBayRules commented
@Saloni242 Any update on this?

2020-09-19 16:15 UTC, closed without merging

2020-09-19 16:16 UTC, Saloni242 commented
New design decided. So we are not working on the previous design.